export const projects = [
  {
    name: "Idea-to-Ipo",
    github: [],
    prod: "",
    skills: ["NextJs", "NodeJS", "Express", "MongoDB"],
    images: ["IdeaToIPO"],
    gist: "A complete listing platform for startups and companies. All the information about different startups. A concept similar to angel.co.",
    description: [
      "A complete listing platform for startups and companies. It provides information about more than 10,000 companies (as of now) to the public giving them a greater reach and valuable information about them to investors and talents.",
      "Created the whole database from scratch by scraping data from various sources using puppeteer and structuring the raw data into a proper schema.",
      "Made the frontend in NextJS to provide SSR in order to benefit SEO and google rankings. Applied authentication and routing on both server and client-side. Includes Role-based access control for different user roles.",
      "The project is in the testing phase and will soon be deployed into production.",
    ],
  },
  {
    name: "What to watch today",
    github: ["https://github.com/atul-gairola/what-to-watch-today"],
    prod: "https://atul-gairola.github.io/what-to-watch-today/",
    skills: ["ReactJS", "Firebase"],
    images: ["WhatToWatchTodaySS1"],
    gist: "Know the feeling of scrolling through OTT platforms everday for 30-40 mins just to choose the same old show to watch. This application is like a movie or show roulette, let it choose what you should watch today and make movie nights more exciting.",
    description: [
      "A fun web app which decides a movie or a tv for the user to watch to save them the trouble of deciding what to watch everyday. User can set some filters or leave it completely random.",
      "Consumes TMDB API to get data about movies and tv shows.",
      "Designed and developed a fully responsive user-friendly UI considering the ease of use to the end-user.",
      "Uses firebase for database and authentication.",
    ],
  },
  {
    name: "LinkedIn CRM",
    github: [
      "https://github.com/atul-gairola/LinkedIn-crm-extension",
      "https://github.com/atul-gairola/LinkedIn-crm-backend-",
    ],
    prod: "",
    skills: ["ReactJs", "NodeJS", "Express", "MongoDB"],
    images: ["LinkedInCRMImage"],
    gist: "A chromium extension which acts as a dashboard for your Linkedin connections. Get a clean tabular UI showing all your connections, send them messages from the dashboard, add tags to them, disconnect old connections and much more.",
    description: [
      "This is a complete clone of LeadDelta chrome extension which is basically a LinkedIn Dashbords to access your network easily. Send mulitple messages, add tags, download connections data.",
      "Consumes TMDB API to get data about movies and tv shows.",
      "Designed and developed a fully responsive user-friendly UI considering the ease of use to the end-user.",
      "Uses firebase for database and authentication.",
    ],
  },
  {
    name: "2-Bound",
    github: [],
    prod: "https://chrome.google.com/webstore/detail/2bound/bioaogffmfdlaecggogedaopceibjklj",
    skills: ["ReactJS", "NodeJS", "Express", "MongoDB"],
    gist: "This extension is for facebook group admins. They can collect the data of their member requests, see it in a dashboard, even export it as a csv.",
    description: [
      "Chromium extension for facebook group admins. Admins can collect data about their member requests and even analyse that data to convert members into clients.",
      "Server in NodeJS using an express framework with authentication, RBAC, and routing.",
      "Created an admin panel for project admins to have an easy access to project and user data.",
    ],
  },
  {
    name: "Covid India Dashboard",
    github: ["https://github.com/atul-gairola/covid-19-india-dashboard"],
    prod: "https://atul-gairola.github.io/covid-19-india-dashboard/",
    skills: ["ReactJS", "RestAPI"],
    gist: "This is my submission mark14 for neoG camp. This app tells if selling the stock gave us profit or loss with the % of the exchange.",
    description: [
      "React dashboard showing covid stats in India and all of its states. The data is consumed through a public REST API and then managed across the application.",
      "Made the UI responsive for all device sizes.",
    ],
  },
  {
    name: "Profit or Loss",
    github: ["https://github.com/atul-gairola/profit-or-loss-mark14"],
    prod: "https://profit-or-loss-mark14.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "This is my submission mark14 for neoG camp. This app tells if selling the stock gave us profit or loss with the % of the exchange.",
    description: [
      "This is my submission mark14 for neoG camp. This app calculates the profit or loss of selling a stock. It returns the percentage of the profit/loss.",
    ],
  },
  {
    name: "Pallindrome Birthdays",
    github: ["https://github.com/atul-gairola/pallindrome-birthday-mark13"],
    prod: "https://pallindrome-birthdays.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "A web app which tells the user if their birthday is palindrome or not. If not, then it tells when is/was the nearest palindrome date and by how much days did you missed to have a palindrome birthday.",
    description: [
      "This is my mark13 submission for neoG camp. This app tells if your birthday is a pallindrome and if not gives the nearest birthday.",
      "A web app which tells the user if their birthday is palindrome or not. If not, then it tells when is/was the nearest palindrome date and by how much days did you missed to have a palindrome birthday.",
    ],
  },
  {
    name: "Do you know your triangles",
    github: ["https://github.com/atul-gairola/do-you-know-your-triangles"],
    prod: "https://do-you-know-your-triangles-mark-12.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "A web app where you can learn more about triangles. It has got a fun quiz on triangles, area calculator for triangle, to check if some lengths would make a triangle or not and functionality to calculate hypotenuse of a right-angled triangle",
    description: [
      "This is my submission for mark12 for neoG camp. This reactjs app is all around triangles. With multiple features dedicated to triangles, play with them and get to know your triangles better.",
      "A web app where you can learn more about triangles. It has got a fun quiz on triangles, area calculator for triangle, to check if some lengths would make a triangle or not and functionality to calculate hypotenuse of a right-angled triangle",
    ],
  },
  {
    name: "Is your birthday lucky?",
    github: ["https://github.com/atul-gairola/is-your-birthday-lucky-mark11"],
    prod: "https://is-your-birthday-lucky-123.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "A fun web app to check if your birthday is lucky or not! Takes your birthday and your lucky number as an input.",
    description: [
      "A fun web app to check if your birthday is lucky or not! Takes your birthday and your lucky number as an input.",
      "Decides if your birthday is lucky - mark11 submission",
    ],
  },
  {
    name: "Cash Register",
    github: ["https://github.com/atul-gairola/cash-register---mark10"],
    prod: "https://cash-register-123.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "A cash register manager which helps the user by telling how can he/she return the change to the customer with minimum number of notes.",
    description: [
      "A cash register manager which helps the user by telling how can he/she return the change to the customer with minimum number of notes.",
      "This is my mark 10 submission - The cash register. This takes in total amount and given cash as input and returns the change that needs to be paid.",
    ],
  },
  {
    name: "Movie Recommendations",
    github: ["https://github.com/atul-gairola/Movie-Recommendations---Mark910"],
    prod: "https://my-movie-recommendations.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "React app which gives movie recommendations on various genres",
    description: [
      "React app which gives movie recommendations on various genres",
      "This is my mark9 submission for neoG camp level 1.",
    ],
  },
  {
    name: "Emoji Interpreter",
    github: ["https://github.com/atul-gairola/Emoji-Interpreter---Mark8"],
    prod: "https://emojieinterpreter.netlify.app/",
    skills: ["ReactJS", "HTML", "CSS"],
    gist: "Compilied data for more than 4000+ emojis and their meaning for people like me, who sometimes have difficulty interpreting emojis about what they mean.",
    description: [
      "This app tells you the name of emoji you enter. This is my mark8 submission",
      "Compilied data for more than 4000+ emojis and their meaning for people like me, who sometimes have difficulty interpreting emojis about what they mean.",
    ],
  },
  {
    name: "Groot Speak",
    github: ["https://github.com/atul-gairola/Groot-speak---mark7"],
    prod: "https://groot-tongue.netlify.app/",
    skills: ["Javascript", "HTML", "CSS", "API"],
    gist: "Translate English sentences and words into groot tongue. This is the mark7 submission for neoG camp.",
    description: [
      "Translates input text into minion language using an api in vanilla JS. This is the mark6 submission for neoG camp.",
    ],
  },
  {
    name: "Minions Speak",
    github: ["https://github.com/atul-gairola/Minions-Speak---Mark6"],
    prod: "https://minion-tongue-converter.netlify.app/",
    skills: ["Javascript", "HTML", "CSS", "API"],
    gist: "Translates input text into minion language using an api in vanilla JS. This is the mark6 submission for neoG camp.",
    description: [
      "Translates input text into minion language using an api in vanilla JS. This is the mark6 submission for neoG camp.",
    ],
  },
  {
    name: "Fandom Quiz App",
    github: ["https://github.com/atul-gairola/Fandom-quiz-app---mark2"],
    prod: "https://replit.com/@atulgairola/mark2",
    skills: ["Javascript", "NodeJS"],
    gist: "A CLI based quiz made with NodeJS on Space and it's mysteries. Test how much do you actually know about Space.",
    description: [
      "A CLI based quiz made with NodeJS on Space and it's mysteries. Test how much do you actually know about Space.",
    ],
  },
  {
    name: "How well do you know me?",
    github: ["https://github.com/atul-gairola/CLI-quiz-app---mark1"],
    prod: "https://replit.com/@atulgairola/Mark1",
    skills: ["Javascript", "NodeJS"],
    gist: "A CLI based quiz made with NodeJS to check how well do you know me. Test how much do you actually know about me.",
    description: [
      "A CLI based quiz made with NodeJS to check how well do you know me. Test how much do you actually know about me.",
    ],
  },
];
